### ISSUE TITLE
Plugin component missing from update site

### ISSUE THREAD

**Issue by phaebz** [veger/eclipse-gef-imageexport#2]
Eclipse: Kepler. There is no `Eclipse GEF ImageExport Plugin` component in the `http://veger.github.com/eclipse-gef-imageexport` update site, only the Batik component.

**Comment by veger** [comment]
Thanks for your report!

A category seems to be missing (which is required by Eclipse 4.x?). When you deselect 'Group items by category' the image export features are shown...

I'll look into it in order to properly fix it (but I am somewhat inexperienced with p2/update sites, so it might take a little time)

**Comment by phaebz** [comment]
Your workaround works. No hurry to properly fix it. Feel free to close and open a more specific issue, e.g. regarding Kepler 4.3.

I am using Papyrus 0.10.1 which still has Incubator status and is buggy on the built-in image export. 

Thanks a bunch for this plugin!

**Comment by veger** [comment]
It now works (tried with a fresh Kepler 'Eclipse Modeling Tools' download for Linux 64 bit)

**Comment by phaebz** [comment]
Nice. Thanks for the quick fix!
